apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sidecar-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sidecar-app
  template:
    metadata:
      labels:
        app: nginx-sidecar-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/share/nginx/html

        - name: sidecar-container
          image: busybox
          command: ["sh", "-c"]
          args:
            - >
              while true; do
                echo "$(date) - Hello from sidecar" >> /data/log.txt;
                echo "Hello from sidecar via PVC" > /data/index.html;
                sleep 10;
              done
          volumeMounts:
            - name: shared-storage
              mountPath: /data

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: sidecar-shared-pvc
