apiVersion: v1
kind: Service
metadata:
  name: nginx-sidecar-service
spec:
  type: NodePort
  selector:
    app: nginx-sidecar-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
